# Generated by Django 4.1.7 on 2023-03-13 10:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.UUID("ff983f20-37a2-478e-8724-aac73d4fb6f6"),
                        editable=False,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("users", "users"), ("products", "products")],
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("description", models.TextField(max_length=155)),
            ],
        ),
    ]
